### ALUNOS

### 

POST http://localhost:5000/alunos 
content-type: application/json

{
    "nome": "João da Silva",
    "fk_cursos_id":1
}

### 

GET http://localhost:5000/alunos

### 

GET http://localhost:5000/alunos/1

###

PUT http://localhost:5000/alunos/6
content-type: application/json

{
    "nome": "Joãozinho"
}

###

DELETE http://localhost:5000/alunos/1